POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video 01",
    "description": "Description of video 01",
    "duration": "180"
}

###

GET http://localhost:3333/videos

###

GET http://localhost:3333/videos?search=01

###

PUT http://localhost:3333/videos/79c7f721-2195-4fd8-b719-ded215463523
Content-Type: application/json

{
    "title": "Video 02 Updated",
    "description": "Description of video 02",
    "duration": "120"
}

###

DELETE http://localhost:3333/videos/79c7f721-2195-4fd8-b719-ded215463523